context:
  version: "2.0.0"

package:
  name: himalaya
  version: ${{ version }}

source:
  url: https://github.com/soywod/himalaya/archive/v${{ version }}.tar.gz
  sha256: 0f58a5761490c2a96105073358487fa6032c79c0f07e962a65f6e8aeef782fd9

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
    - libgit2 <1.9
  host:
    - openssl

tests:
  - script:
      - himalaya --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: CLI email client written in Rust
  homepage: https://github.com/soywod/himalaya
  repository: https://github.com/soywod/himalaya

extra:
  recipe-maintainers:
    - danielnachun
